version: 2.1

jobs:
  build:
    docker:
      - image: node:20
    resource_class: large
    parallelism: 10

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            npm install --global corepack@latest
            corepack enable
            corepack prepare pnpm@latest-10 --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store

  build:
    docker:
      - image: node:20
    steps:
      - checkout
      - run:
          name: Setup PNPM
          command: |
            curl -fsSL https://get.pnpm.io/install.sh | sh -
            pnpm config set store-dir ~/.pnpm-store
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Build
          command: |
            pnpm run build
            ls dist
      - save_cache:
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist

  test:
    docker:
      - image: node:20
    steps:
      - checkout
      - run:
          name: Setup PNPM
          command: |
            curl -fsSL https://get.pnpm.io/install.sh | sh -
            pnpm config set store-dir ~/.pnpm-store
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Test
          command: pnpm test:unit run

  deploy:
    docker:
      - image: node:20
    steps:
      - checkout
      - run:
          name: Setup PNPM
          command: |
            curl -fsSL https://get.pnpm.io/install.sh | sh -
            pnpm config set store-dir ~/.pnpm-store
      - restore_cache:
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
      - deploy:
          name: Deploy gh-pages to Github Pages
          command: './deploy.sh dist'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master