version: 2
jobs:
  setup:
    docker:
      - image: guergeiro/pnpm:18-8
    steps:
      - checkout
      - run:
          name: Versions
          command: |
            node --version
            pnpm --version
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
          - node_modules
  build:
    docker:
      - image: guergeiro/pnpm:18-8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Build
          command: |
            pnpm run build
            ls dist
      - save_cache:
          key: build-output-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist
  test:
    docker:
      - image: guergeiro/pnpm:18-8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Test
          command: pnpm test:unit run
  deploy:
    docker:
      - image: guergeiro/pnpm:18-8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - deploy:
          name: Deploy gh-pages to Github Pages
          command: './deploy.sh dist'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
