version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12.0.0-browsers
        steps:
            - checkout
            - run:
                name: Versions
                command: |
                    node --version
                    npm --version
                    yarn --version
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: rebuild node-sass
                command: npm rebuild node-sass
            - run:
                name: Install npm dependencies
                command: 'npm install'
            - run:
                name: Running production build
                command: 'npm run build'
            - persist_to_workspace:
                root: .
                paths: .
    deploy:
        docker:
            - image: circleci/node:12.0.0-browsers
        steps:
            - checkout
            - run:
                name: Versions
                command: |
                    node --version
                    npm --version
                    yarn --version
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: rebuild node-sass
                command: npm rebuild node-sass
            - run:
                name: Install npm dependencies
                command: 'npm install'
            - run:
                name: Build
                command: 'npm run build'
            - deploy:
                name: Deploy gh-pages to Github Pages
                command: './deploy.sh dist'

workflows:
    version: 2
    build-deploy:
        jobs:
        - build:
            filters:
                branches:
                    ignore:
                        - gh-pages
        - deploy:
            requires:
                - build
            filters:
                branches:
                    only: master
